version: '3'

services:
  server:
    build: 
      context: ./server
      dockerfile: Dockerfile

  client:
    build: 
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
